import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { MatExpansionModule } from '@angular/material/expansion';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatTableModule } from '@angular/material/table';
import { MatSortModule } from '@angular/material/sort';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatMenuModule } from '@angular/material/menu';
import { MatToolbarModule,
         MatCardModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatRadioModule,
         MatSelectModule,
         MatInputModule,
         MatPaginatorModule,
         MatButtonModule,
         MatTooltipModule,
         MatIconModule,
         MatDividerModule,
         MatProgressSpinnerModule,
         MatAutocompleteModule,
         MatBadgeModule,
         MatBottomSheetModule,
         MatButtonToggleModule,
         MatChipsModule,
         MatDialogModule,
         MatGridListModule,
         MatListModule,
         MatProgressBarModule,
         MatRippleModule,
         MatSidenavModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSnackBarModule,
         MatStepperModule,
         MatTabsModule,
         MatTreeModule } from '@angular/material';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
    declarations: [],
    imports: [
        CommonModule,
        BrowserAnimationsModule,
        MatExpansionModule,
        MatMenuModule,
        MatToolbarModule,
        FlexLayoutModule,
        MatCardModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatRadioModule,
        MatSelectModule,
        MatInputModule,
        MatPaginatorModule,
        MatButtonModule,
        MatMenuModule,
        FlexLayoutModule,
        MatTooltipModule,
        MatIconModule,
        MatDividerModule,
        MatSortModule,
        MatTableModule,
        MatProgressSpinnerModule,

        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatDialogModule,
        MatGridListModule,
        MatListModule,
        MatProgressBarModule,
        MatRippleModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTabsModule,
        MatTreeModule,

    ],
    exports: [
        MatExpansionModule,
        BrowserAnimationsModule,
        FlexLayoutModule,
        MatTableModule,
        MatSortModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatMenuModule,
        MatToolbarModule,
        MatCardModule,
        MatDatepickerModule,
        // MatNativeDateModule,
        MatRadioModule,
        MatSelectModule,
        MatInputModule,
        MatPaginatorModule,
        MatButtonModule,
        MatMenuModule,
        FlexLayoutModule,
        MatTooltipModule,
        MatIconModule,
        MatDividerModule,
        MatProgressSpinnerModule,

        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatDialogModule,
        MatGridListModule,
        MatListModule,
        MatProgressBarModule,
        MatRippleModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatStepperModule,
        MatTabsModule,
        MatTreeModule,
    ],
    providers: [],
})
export class MaterialModule {}
